from enum import Enum

class EvidenceStatus(str, Enum):
    PROVEN = "PROVEN"
    PARTIALLY_PROVEN = "PARTIALLY_PROVEN"
    UNVERIFIED = "UNVERIFIED"
    CONTRADICTED = "CONTRADICTED"
    NOT_FOUND_IN_PROVIDED_MATERIAL = "NOT_FOUND_IN_PROVIDED_MATERIAL"

class RequirementCategory(str, Enum):
    MUST_HAVE = "MUST_HAVE"
    NICE_TO_HAVE = "NICE_TO_HAVE"

class GapPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class SourceType(str, Enum):
    RESUME = "RESUME"
    INTERVIEW_NOTE = "INTERVIEW_NOTE"
    RECRUITER_OVERRIDE = "RECRUITER_OVERRIDE"

class InterviewSessionStatus(str, Enum):
    DRAFT = "DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REVIEWED = "REVIEWED"
    QUARANTINED = "QUARANTINED"

class InterviewProposalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class AIMode(str, Enum):
    LIVE_GEMINI = "LIVE_GEMINI"
    LIVE_GROQ = "LIVE_GROQ"
    OFFLINE_FALLBACK = "OFFLINE_FALLBACK"

class AuditAction(str, Enum):
    ROLE_CREATED = "ROLE_CREATED"
    CANDIDATE_INGESTED = "CANDIDATE_INGESTED"
    EVIDENCE_MATCHED = "EVIDENCE_MATCHED"
    SCORE_CALCULATED = "SCORE_CALCULATED"
    INTERVIEW_GENERATED = "INTERVIEW_GENERATED"
    INTERVIEW_SESSION_CREATED = "INTERVIEW_SESSION_CREATED"
    INTERVIEW_NOTES_ADDED = "INTERVIEW_NOTES_ADDED"
    INTERVIEW_EVIDENCE_PROPOSED = "INTERVIEW_EVIDENCE_PROPOSED"
    INTERVIEW_EVIDENCE_APPROVED = "INTERVIEW_EVIDENCE_APPROVED"
    INTERVIEW_EVIDENCE_REJECTED = "INTERVIEW_EVIDENCE_REJECTED"
    SCORE_RECALCULATED = "SCORE_RECALCULATED"
    GAPS_RECALCULATED = "GAPS_RECALCULATED"
    RECRUITER_OVERRIDE = "RECRUITER_OVERRIDE"
    SECURITY_QUARANTINE = "SECURITY_QUARANTINE"
    CRITERION_CREATED = "CRITERION_CREATED"
    CRITERION_DELETED = "CRITERION_DELETED"
    INTERVIEW_STARTED = "INTERVIEW_STARTED"
    QUESTION_PRESENTED = "QUESTION_PRESENTED"
    ANSWER_CAPTURED = "ANSWER_CAPTURED"
    EVIDENCE_CONFIRMED = "EVIDENCE_CONFIRMED"
    FOLLOWUP_GENERATED = "FOLLOWUP_GENERATED"
    QUESTION_SKIPPED = "QUESTION_SKIPPED"
    REQUIREMENT_UPDATED = "REQUIREMENT_UPDATED"
    INTERVIEW_ENDED = "INTERVIEW_ENDED"

class AuditActor(str, Enum):
    SYSTEM_AGENT = "SYSTEM_AGENT"
    RECRUITER = "RECRUITER"
